### ISSUE TITLE
Change Napari "rotate" with something that makes more sense

### ISSUE THREAD

**Issue by horsto** [brainglobe/brainreg-segment#14] opened 2020-09-03 09:02 UTC
Currently, rotating e.g. a mouse brain results in weird views, where the brain is upside down / doesn't quite fit into the canvas. 
The Napari rotate button / function can be overwritten with something that follows bg space conventions. A possible route is something like this: 

```
ORIENTATIONS = ['asl','lsa','sla']  # When rolling through orientations of the brain, adhere to this order


def get_dims_from_origins(origins):
    ''' From a list of BG space abbreviations (e.g. ["asl","sla","lsa"]) get correct axes for display in Napari ''' 
    all_dims = []
    for o in range(len(origins)):
        sc = bg.SpaceConvention(origins[0]) 
        next_orientation = origins[(o+1)%len(origins)]
        dims, flips, _, _ = sc.map_to(next_orientation)
        assert not any(flips), f'\nReceived orientations: {origins}\nThese require (orientation) flips. This is not currently supported'
        all_dims.append(list(dims))
    return all_dims


def overwrite_napari_roll(viewer):
    ''' 
    Overwrite Napari _roll() function with something that makes more sense for a (mouse) brain
    Goal: Cycle through views (e.g. asl -> lsa -> sal)
    '''
    dims = get_dims_from_origins(ORIENTATIONS)

    def _roll(self):
        """Roll order of dimensions for display."""
        dims_idx  = dims.index(self.order)
        next_dims = dims[(dims_idx+1)%len(dims)]
        self.order = next_dims      
          
    # Substitute Napari function
    napari.components.dims.Dims._roll = _roll

```

(taken from code I had previously written when I started with this separately from brainreg-segment)

**Comment by adamltyson** [comment] 2020-09-03 09:04
That looks great. Would you mind submitting a PR? 

A (very) minor complication is that the orientation definition of all brainglobe atlases will move to `asr`.

**Comment by horsto** [comment] 2020-09-03 09:05
Yes, I can test that a bit more probably this evening. You are right: This is still the "old" assumption of `asl`.

**Comment by adamltyson** [comment] 2020-09-03 09:24
> Jumping in only to say that this is going in an amazing direction rocket

haha, thanks! GitHub needs professional cheerleaders!

**Comment by adamltyson** [comment] 2020-09-03 09:31
I'd be interested in @sofroniewn's thoughts here, following our chat about eventually moving all of these whole-brain analysis tools into napari proper (as plugins etc.).

@sofroniewn - We're gradually getting a little bit more professional in how we're using napari, including things like hiding napari buttons that don't make sense for our application, and this issue about overwriting buttons to better fit with our data. This in particular will come up regularly, so I wondered if you had thoughts about how best to do this for better integration with napari down the line (which I'm super keen on now the bundled apps are released!).

**Comment by vigji** [comment] 2020-09-03 09:57
In particular, I would be very interested in finding a nice, general way (easy to apply outside here) of integrating somehow the semantic description of anatomical axes using (bg-space)[https://github.com/brainglobe/bg-space] (maybe with a plugin, don't know what will be the future plans on hooks provided to login developers) to integrate nicely with `napari` to show axes labels and toggling dimensions in a "meaningful" way

**Comment by adamltyson** [comment] 2020-09-04 10:43
(Nearly) fixed in d3b0dd352e7f2a081f131377b764418bfcd4d078. 

Leaving this open to keep track, but maybe this is fully fixed in the new bg-atlaspi atlases.

**Comment by sofroniewn** [comment] 2020-09-04 16:08
> @sofroniewn - We're gradually getting a little bit more professional in how we're using napari, including things like hiding napari buttons that don't make sense for our application, and this issue about overwriting buttons to better fit with our data. This in particular will come up regularly, so I wondered if you had thoughts about how best to do this for better integration with napari down the line (which I'm super keen on now the bundled apps are released!).

Hi @adamltyson, I think here we're just going to have to start trying things and see how it goes. The was a lot of discussion here https://github.com/napari/napari/issues/1327 about opening up an `add_dock_widget` hook spec which would let the plugin add dock widgets. We've also been thinking about how to add custom keybindings/ mouse functions.

I'll be honest I hadn't thought yet about overwriting/ removing buttons from the interface in a custom way, and I'd probably want to do that as a last resort, instead asking if there is a way we can change the button so that it actually worked better for everyone or just remove the button as too specific/ not functioning as intended.

For example here it sounds like the `roll_axes` button is causing problems, that makes sense to me if I think about anyone with volumetric timeseries data who accidentally rolls so that time is now one of the visualized dimensions. I'm not sure how I'd fix that within napari right now, and maybe overwriting/ customizing etc is going to be the right way to handle it, but then we'd want to make that really easy.

**Comment by adamltyson** [comment] 2020-09-04 16:50
Hi @sofroniewn, thanks for your reponse.

>  is a way we can change the button so that it actually worked better for everyone or just remove the button as too specific/ not functioning as intended.

In our case, it's not that there's anything "wrong" with the button, but that it confuses the UI for our application. As an example, we have segmentation workflows that rely on a points/labels layer. Rather than users adding a new structure to segment by clicking on e.g. "New labels layer" button, they click our "Add region" button, which adds a new labels layer, but also initializes lots of stuff for downstream processing. Removing the native napari buttons makes things less confusing for the user, as otherwise there would be one way of adding a labels layer that functions properly, and one that doesn't. Hope this makes sense, and I can see how it may not work well when these tools are more tightly integrated with napari in the future. 

> For example here it sounds like the roll_axes button is causing problems, that makes sense to me if I think about anyone with volumetric timeseries data who accidentally rolls so that time is now one of the visualized dimensions. I'm not sure how I'd fix that within napari right now, and maybe overwriting/ customizing etc is going to be the right way to handle it, but then we'd want to make that really easy.

I can't see there being a general solution to this, other than maybe some presets, so plugin developers could choose the most sensible for their application. 

My general concern is that every time we "customise" napari for our own needs, we move further away from becoming a napari extension in the future. I'd **much** prefer for our tools to become napari extensions, rather than always build on top of napari as we do currently. Realistically, anything we build on top of napari in our own way, won't work in two years time without ongoing maintenance.

**Comment by sofroniewn** [comment] 2020-09-04 17:51
> Removing the native napari buttons makes things less confusing for the user, as otherwise there would be one way of adding a labels layer that functions properly, and one that doesn't. Hope this makes sense, and I can see how it may not work well when these tools are more tightly integrated with napari in the future.
>
> I can't see there being a general solution to this, other than maybe some presets, so plugin developers could choose the most sensible for their application.

Hmm, yeah this use case is tricky. One option is to make the whole row of "new points", "new labels" etc buttons its own dock widget and then make it easy for plugins to make the whole viewer "locked", (as in discussion here https://github.com/napari/napari/issues/1570) and maybe then hide those buttons when the viewer is locked. A plugin might then be able to additionally provide its own ways to edit the viewer like your regions button.

> My general concern is that every time we "customise" napari for our own needs, we move further away from becoming a napari extension in the future. I'd much prefer for our tools to become napari extensions, rather than always build on top of napari as we do currently. Realistically, anything we build on top of napari in our own way, won't work in two years time without ongoing maintenance.

Absolutely, I'm so glad you prefer this option and the napari team really is committed to working over the next year to making this possible. I think if we open up the dock widget spec that will let us start getting some of your simple functionality in, and then we can work out from there. I know @tlambert03 was excited to work on https://github.com/napari/napari/issues/1327 and maybe we can try and get that into our next big release.

One guiding workflow that I think we want to make sure is possible is that a user could from the bundled app install your tool, "activate it" which would add your UI elements/ functionality, and then "deactiviate it" so to that napari would return to it's base UI but the data would remain as is, so that someone could then "activate" another tool on data after it had been processed by your tool, thereby allowing tools to work together (i.e. do segmentation after registration, or tracking after segmentation).

**Comment by adamltyson** [comment] 2020-09-07 11:08
> One guiding workflow that I think we want to make sure is possible is that a user could from the bundled app install your tool, "activate it" which would add your UI elements/ functionality, and then "deactiviate it" so to that napari would return to it's base UI but the data would remain as is, so that someone could then "activate" another tool on data after it had been processed by your tool, thereby allowing tools to work together (i.e. do segmentation after registration, or tracking after segmentation).

Agree. I'm trying to compartmentalise everything as far as possible so that users can mix and match methods. The only thing that I'm not too clear on, is how to implement multiple coordinate spaces (which is a key part of our analysis).

Broadly speaking "normal" data analysis (cell segmentation etc.) happens in a variety of sample coordinate spaces, and varied registration workflows define the transformation of these images (and detected features) into a common space. I might have missed it, but are there any discussions on how to approach this within napari? Maybe standard ways of describing the transforms?

**Comment by adamltyson** [comment] 2020-12-09 15:57
Closing this, as it can probably be dealt with by https://github.com/napari/napari/issues/1929

**Closed by adamltyson** 2020-12-09 15:57 UTC
